### ISSUE TITLE
Ok, Beekepeer is busy on npm

### ISSUE THREAD

**Issue by den-t** [Hospo360/bee-queue-ui#1]
We need to name the package so it wouldn't clash with what is already there.
Please feel free to create an account on npm.
Also readme, package.json, and some titles should be changed to reflect the new package name.

**Comment by den-t** [comment]
bee-queue-ui?

**Comment by den-t** [comment]
bee-queue-ui? It's free.

**Comment by KellyKMK89** [comment]
I'm using bee-queue-ui for the package name
