### ISSUE TITLE
Support non-standard queue prefix

### ISSUE THREAD

**Issue by harto** [Hospo360/bee-queue-ui#23]
Bee-queue supports setting the Redis key prefix to something other than `bq` (https://github.com/LewisJEllis/bee-queue#settings). When pointed at such a queue instance, bee-queue-ui shows no jobs. Could this be made configurable?

**Comment by harto** [comment]
I'm happy to implement this if you advise your preference on how to pass the custom prefix around. E.g. thread it into all the methods that generate Redis keys, or store it in some global variable, etc.

**Comment by den-t** [comment]
Sorry it was a long weekend here.

We'll need to extend settings object in `config/[development|production].json` to showcase the default `bq` prefix. With regards to passing the prefix around I'm inclined to use one of these:

Option 1.
Have it as a global variable. It can be obtained from the `options` in `setupAndMiddleware.js`. Already using `redis` global variable inside the functions, thus we can as well add another one.
Not really fond of it, but is a lot easier to do. So if you are keen please proceed with it.

Option 2.
Convert `models/redis.js` into a singleton and initialise it with redis connection and prefix.
I'll create another issue for it, as it's a biggie.

**Comment by harto** [comment]
OK, I'll create another global as suggested, and leave it to you to do the bigger refactor if/when you want to ;-)
